/**
 * This class provides a method to add two numbers.
 */
public class AddNumbers {

    /**
     * Adds two integers and returns the result.
     *
     * @param a the first integer
     * @param b the second integer
     * @return the sum of a and b
     */
    public static int add(int a, int b) {
        return a + b;
    }

    /**
     * Main method to test the add function.
     *
     * @param args command-line arguments (not used here)
     */
    public static void main(String[] args) {
        int num1 = 1000;
        int num2 = 200;
        int sum = add(num1, num2);

        
        System.out.println("The sum of Two numbers are  " + num1 + " and " + num2 + " is: " + sum);
        System.out.println("Sum is Generated by java\n");
    }
}